endpoint_url: "http://localhost:8080/invocations"
module_name: "llama3_prompt_generator"
module_dir: "modules/inst-semeval2017"
prompt_generator: "PromptGenerator"
template: { 
  "model": "lmi", 
  "max_tokens": 2048, 
  "top_k": 50, 
  "messages": [ 
    { 
      "role": "user", 
      "content": "" 
    } 
  ] 
}
template_keys: ["messages.[0].content"]