endpoint_url: "http://localhost:8080/v2/models/model/infer"
module_name: "token_classification_prompts"
module_dir: "modules/conll2003"
prompt_generator: "TokenClassificationInputGenerator"
template: {
  "inputs": [
    {
      "name": "text_input",
      "shape": [1, 1], 
      "datatype": "BYTES",
      "data": []
    }
  ]
}
template_keys: ["inputs.[0].data"]